package c2pa

import (
	"bytes"
	"compress/zlib"
	"context"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/veraison/go-cose"
)

// TestPDFOpenAIFixture is the PDF container on a real producer's file rather
// than a synthesised one. The document was generated by ChatGPT, so its carrier
// is what that pipeline writes: a catalog at generation 1, /Type /FileSpec, a
// literal-string /Subtype, and the manifest added by an incremental update. It
// is also the only fixture here whose manifest carries no timestamp at all.
func TestPDFOpenAIFixture(t *testing.T) {
	data, err := os.ReadFile("testdata/c2pa_chatgpt.pdf")
	if err != nil {
		t.Fatal(err)
	}

	info := Read(context.Background(), PDF, bytes.NewReader(data))
	for _, tc := range []struct{ name, got, want string }{
		{"ClaimGenerator", info.ClaimGenerator, "ChatGPT"},
		{"SoftwareAgent", info.SoftwareAgent, "gpt-5.6-sol/gpt-5.6-sol"},
		{"Title", info.Title, "image.pdf"},
		{"SignedBy", info.SignedBy, "OpenAI Media Service"},
	} {
		if tc.got != tc.want {
			t.Errorf("Read %s=%q want %q", tc.name, tc.got, tc.want)
		}
	}
	if !info.AIGenerated {
		t.Error("Read AIGenerated=false, want true")
	}
	if !info.SignedAt.IsZero() {
		t.Errorf("Read SignedAt=%s, want zero: the manifest carries no timestamp", info.SignedAt)
	}

	// Pinned inside the leaf's validity window (2026-04-22 to 2027-04-23). There
	// is no timestamp to pin to, so an unpinned test would start failing the day
	// the leaf expires.
	inWindow := time.Date(2026, 9, 1, 0, 0, 0, 0, time.UTC)
	r := Validate(context.Background(), PDF, bytes.NewReader(data),
		WithClock(func() time.Time { return inWindow }))

	if !r.Valid {
		t.Fatalf("expected valid, got %v", codes(r))
	}
	for _, code := range []StatusCode{
		StatusClaimSignatureValidated,
		StatusSigningCredentialTrusted,
		StatusAssertionDataHashMatch,
	} {
		if !r.Has(code) {
			t.Errorf("expected %s; statuses=%v", code, codes(r))
		}
	}
	// No timestamp at all, where the PNG fixture has an untrusted one.
	if !r.Has(StatusTimeStampMissing) {
		t.Errorf("expected %s; statuses=%v", StatusTimeStampMissing, codes(r))
	}
	if len(r.SignerChain) != 2 {
		t.Errorf("SignerChain has %d certs, want 2", len(r.SignerChain))
	}
}

// TestPDFAdobeReferenceFile reads the C2PA reference PDF, which cannot live in
// testdata: c2pa-org/public-testfiles licenses it CC-BY-SA-4.0 and this
// repository is MIT with Apache-2.0/MIT fixtures. It is the only real producer
// file that proves /Subtype is absent in the wild, so it is worth an opt-in
// test — point C2PA_ADOBE_PDF at it, or have CI download it.
func TestPDFAdobeReferenceFile(t *testing.T) {
	path := os.Getenv("C2PA_ADOBE_PDF")
	if path == "" {
		t.Skip("set C2PA_ADOBE_PDF to adobe-20240110-single_manifest_store.pdf")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	ctx := context.Background()

	if !bytes.Contains(data, []byte("/AFRelationship /C2PA_Manifest")) {
		t.Error("no /AFRelationship /C2PA_Manifest: not the reference file")
	}
	// The claim this pins: the markers the /Subtype fallback looks for are not
	// in this file, on either dictionary, so that fallback is no backstop.
	for _, subtype := range []string{"application#2Fc2pa", "(application/c2pa)"} {
		if bytes.Contains(data, []byte(subtype)) {
			t.Errorf("the reference file carries %s after all", subtype)
		}
	}

	info := Read(ctx, PDF, bytes.NewReader(data))
	if !info.Present {
		t.Fatal("no manifest read from the reference file")
	}
	t.Logf("generator=%q signer=%q", info.ClaimGenerator, info.SignedBy)
	if info.Attribution != AttributionAsset {
		t.Errorf("Attribution = %q, want %q: the catalog chain should attribute the store",
			info.Attribution, AttributionAsset)
	}
}

// --- synthetic PDF builders --------------------------------------------------

// pdfDoc assembles a PDF in memory: a header, indirect objects in the order
// they are appended, and a trailer naming the catalog. It writes no xref table
// — the extractor is a lexical scanner, and what these tests exercise is the
// object bytes. Appending more objects and a second trailer after a first one
// is exactly the shape of a PDF incremental update.
type pdfDoc struct {
	b []byte
	// offs records where each object number's definition starts, which is what
	// a cross-reference table holds; xrefTrailer needs it.
	offs map[int]int
}

func newPDFDoc() *pdfDoc { return &pdfDoc{b: []byte("%PDF-1.7\n"), offs: map[int]int{}} }

func (d *pdfDoc) obj(num int, body string) *pdfDoc {
	d.offs[num] = len(d.b)
	d.b = append(d.b, fmt.Sprintf("%d 0 obj\n%s\nendobj\n", num, body)...)
	return d
}

// stream appends a stream object. length is the literal text of the /Length
// entry, so a test can make it lie or make it indirect; "" writes the truth.
func (d *pdfDoc) stream(num int, dict string, payload []byte, length string) *pdfDoc {
	if length == "" {
		length = fmt.Sprint(len(payload))
	}
	d.offs[num] = len(d.b)
	d.b = append(d.b, fmt.Sprintf("%d 0 obj\n<< %s /Length %s >>\nstream\n", num, dict, length)...)
	d.b = append(d.b, payload...)
	d.b = append(d.b, "\nendstream\nendobj\n"...)
	return d
}

func (d *pdfDoc) trailer(root int) *pdfDoc {
	d.b = append(d.b, fmt.Sprintf("trailer\n<< /Root %d 0 R >>\nstartxref\n0\n%%%%EOF\n", root)...)
	return d
}

// xrefTrailer writes a real cross-reference table over every object appended so
// far and a startxref holding that table's own offset — the route a conforming
// reader takes to the catalog. trailer() writes a startxref of 0, which no
// reader can follow, so only a document ending here exercises the xref path.
func (d *pdfDoc) xrefTrailer(root int) *pdfDoc {
	high := 0
	for num := range d.offs {
		high = max(high, num)
	}
	start := len(d.b)
	d.b = append(d.b, fmt.Sprintf("xref\n0 %d\n0000000000 65535 f \n", high+1)...)
	for num := 1; num <= high; num++ {
		if off, ok := d.offs[num]; ok {
			d.b = append(d.b, fmt.Sprintf("%010d 00000 n \n", off)...)
		} else {
			d.b = append(d.b, "0000000000 65535 f \n"...)
		}
	}
	d.b = append(d.b, fmt.Sprintf("trailer\n<< /Size %d /Root %d 0 R >>\nstartxref\n%d\n%%%%EOF\n",
		high+1, root, start)...)
	return d
}

func (d *pdfDoc) bytes() []byte { return d.b }

// append adds raw bytes with no cross-reference entry of their own, which is
// what tampering after %%EOF looks like.
func (d *pdfDoc) append(s string) *pdfDoc {
	d.b = append(d.b, s...)
	return d
}

// appendUnplacedXref appends a cross-reference section that parses and names its own /Root but
// places no object at all, plus a startxref pointing at it. A decoy needs nothing more than this to
// be the last section a reader looks at.
func (d *pdfDoc) appendUnplacedXref(root int) *pdfDoc {
	start := len(d.b)
	d.b = append(d.b, fmt.Sprintf("xref\n0 1\n0000000000 65535 f \n"+
		"trailer\n<< /Size 1 /Root %d 0 R >>\nstartxref\n%d\n%%%%EOF\n", root, start)...)
	return d
}

// appendMisplacedXref appends a section whose one in-use entry places root at an offset no object
// sits at, plus a startxref naming it. An in-use entry exists, so anything checking only that the
// section placed something accepts it.
func (d *pdfDoc) appendMisplacedXref(root, offset int) *pdfDoc {
	start := len(d.b)
	d.b = append(d.b, fmt.Sprintf("xref\n0 1\n0000000000 65535 f \n%d 1\n%010d 00000 n \n"+
		"trailer\n<< /Size %d /Root %d 0 R >>\nstartxref\n%d\n%%%%EOF\n",
		root, offset, root+1, root, start)...)
	return d
}

// clone copies the document, so an update section can be appended to a fresh
// copy without disturbing the bytes of the original.
func (d *pdfDoc) clone() *pdfDoc {
	c := &pdfDoc{b: append([]byte{}, d.b...), offs: map[int]int{}}
	for num, off := range d.offs {
		c.offs[num] = off
	}
	return c
}

const (
	pdfEmbeddedFileDict = "/Type /EmbeddedFile /Subtype /application#2Fc2pa"
	pdfC2PAFilespec     = "<< /Type /Filespec /F (c2pa.c2pa) /UF (c2pa.c2pa) " +
		"/AFRelationship /C2PA_Manifest /EF << /F 4 0 R >> >>"
)

// synthPDF builds a document whose catalog associates one C2PA manifest, the
// layout spec §A.4 describes: catalog /AF → file specification → /EF stream.
func synthPDF(t *testing.T, store []byte, compress bool) []byte {
	t.Helper()
	dict, payload := pdfEmbeddedFileDict, store
	if compress {
		dict, payload = dict+" /Filter /FlateDecode", zlibBytes(t, store)
	}
	return newPDFDoc().
		obj(1, "<< /Type /Catalog /Pages 2 0 R /AF [3 0 R] >>").
		obj(2, "<< /Type /Pages /Kids [] /Count 0 >>").
		obj(3, pdfC2PAFilespec).
		stream(4, dict, payload, "").
		trailer(1).
		bytes()
}

// zlibBytes compresses b the way a producer writes a /FlateDecode stream.
func zlibBytes(t *testing.T, b []byte) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zlib.NewWriter(&buf)
	if _, err := zw.Write(b); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// --- manifest extraction -----------------------------------------------------

func TestPDFJUMBF(t *testing.T) {
	store := synthJUMB([]byte("manifest store"))
	ctx := context.Background()

	t.Run("uncompressed embedded file", func(t *testing.T) {
		if got := pdfJUMBF(ctx, synthPDF(t, store, false)); !bytes.Equal(got, store) {
			t.Fatalf("store not extracted: got %q", got)
		}
	})
	t.Run("flate-compressed embedded file", func(t *testing.T) {
		if got := pdfJUMBF(ctx, synthPDF(t, store, true)); !bytes.Equal(got, store) {
			t.Fatalf("compressed store not inflated: got %q", got)
		}
	})
	t.Run("padded stream trimmed to the superbox", func(t *testing.T) {
		padded := append(append([]byte{}, store...), make([]byte, 64)...)
		if got := pdfJUMBF(ctx, synthPDF(t, padded, false)); !bytes.Equal(got, store) {
			t.Fatalf("padding not trimmed: got %d bytes, want %d", len(got), len(store))
		}
	})
	t.Run("no associated files", func(t *testing.T) {
		doc := newPDFDoc().obj(1, "<< /Type /Catalog /Pages 2 0 R >>").trailer(1).bytes()
		if got := pdfJUMBF(ctx, doc); got != nil {
			t.Fatalf("document with no manifest yielded %q", got)
		}
	})
	t.Run("foreign relationship ignored", func(t *testing.T) {
		doc := newPDFDoc().
			obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
			obj(3, "<< /Type /Filespec /F (notes.txt) /AFRelationship /Supplement /EF << /F 4 0 R >> >>").
			stream(4, "/Type /EmbeddedFile", store, "").
			trailer(1).bytes()
		if got := pdfJUMBF(ctx, doc); got != nil {
			t.Fatalf("non-C2PA associated file yielded %q", got)
		}
	})
	t.Run("payload that is not JUMBF", func(t *testing.T) {
		if got := pdfJUMBF(ctx, synthPDF(t, []byte("not a manifest at all"), false)); got != nil {
			t.Fatalf("non-JUMBF payload yielded %q", got)
		}
	})
	t.Run("not a PDF", func(t *testing.T) {
		if got := pdfJUMBF(ctx, []byte("\x89PNG\r\n\x1a\n1 0 obj stream")); got != nil {
			t.Fatalf("non-PDF input yielded %q", got)
		}
	})
	t.Run("cancelled context", func(t *testing.T) {
		cancelled, cancel := context.WithCancel(ctx)
		cancel()
		if got := pdfJUMBF(cancelled, synthPDF(t, store, false)); got != nil {
			t.Fatalf("cancelled ctx yielded %q", got)
		}
	})
}

// TestPDFJUMBF_DeclaredLengthLies pins that /Length is a hint: too large, too
// small, or an indirect reference the scanner does not resolve, the payload is
// still bounded by the `endstream` keyword.
func TestPDFJUMBF_DeclaredLengthLies(t *testing.T) {
	store := synthJUMB([]byte("manifest store"))
	for name, length := range map[string]string{
		"far too large": "999999999",
		"too small":     "3",
		"negative":      "-40",
		"indirect ref":  "9 0 R",
	} {
		t.Run(name, func(t *testing.T) {
			doc := newPDFDoc().
				obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
				obj(3, pdfC2PAFilespec).
				stream(4, pdfEmbeddedFileDict, store, length).
				trailer(1).bytes()
			if got := pdfJUMBF(context.Background(), doc); !bytes.Equal(got, store) {
				t.Fatalf("/Length %s: got %q want the store", length, got)
			}
		})
	}
}

// TestPDFInt pins that an indirect reference reports absent rather than its
// object number. The stream reader survives either way, because it verifies a
// declared length against `endstream`, but a future caller without that fallback
// would otherwise read 9 as a byte count.
func TestPDFInt(t *testing.T) {
	for name, tc := range map[string]struct {
		dict string
		want int
		ok   bool
	}{
		"direct":                  {"<< /Length 40 >>", 40, true},
		"indirect ref":            {"<< /Length 9 0 R >>", 0, false},
		"indirect ref, no spaces": {"<< /Length 9 0 R/Type /X >>", 0, false},
		"absent":                  {"<< /Type /X >>", 0, false},
		"not a number":            {"<< /Length /X >>", 0, false},
	} {
		t.Run(name, func(t *testing.T) {
			got, ok := pdfInt([]byte(tc.dict), "Length")
			if got != tc.want || ok != tc.ok {
				t.Fatalf("pdfInt(%q) = (%d, %v), want (%d, %v)", tc.dict, got, ok, tc.want, tc.ok)
			}
		})
	}
}

// TestPDFJUMBF_IncrementalUpdate pins the "last definition wins" rule: an
// update appends a new catalog and a new manifest without touching the original
// bytes, and the newest association is the current one.
func TestPDFJUMBF_IncrementalUpdate(t *testing.T) {
	first := synthJUMB([]byte("first manifest"))
	second := synthJUMB([]byte("second manifest"))
	ctx := context.Background()

	base := newPDFDoc().
		obj(1, "<< /Type /Catalog /Pages 2 0 R /AF [3 0 R] >>").
		obj(2, "<< /Type /Pages /Kids [] /Count 0 >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, first, "").
		trailer(1)
	if got := pdfJUMBF(ctx, base.bytes()); !bytes.Equal(got, first) {
		t.Fatalf("base document: got %q want the first manifest", got)
	}

	t.Run("re-signed", func(t *testing.T) {
		doc := base.clone().
			obj(1, "<< /Type /Catalog /Pages 2 0 R /AF [5 0 R] >>").
			obj(5, "<< /Type /Filespec /F (c2pa.c2pa) /AFRelationship /C2PA_Manifest /EF << /F 6 0 R >> >>").
			stream(6, pdfEmbeddedFileDict, second, "").
			trailer(1).bytes()
		if got := pdfJUMBF(ctx, doc); !bytes.Equal(got, second) {
			t.Fatalf("got %q want the manifest the update associated", got)
		}
	})
	t.Run("association dropped by the update", func(t *testing.T) {
		// §A.4.2.1 makes the catalog's /AF the active manifest, so a catalog
		// associating none leaves the document claiming no provenance. The
		// superseded store is still in the bytes and still surfaced — as
		// something the document does not vouch for, not as its manifest.
		doc := base.clone().
			obj(1, "<< /Type /Catalog /Pages 2 0 R /AF [5 0 R] >>").
			obj(5, "<< /Type /Filespec /F (notes.txt) /AFRelationship /Supplement >>").
			trailer(1).bytes()
		if got := pdfJUMBF(ctx, doc); !bytes.Equal(got, first) {
			t.Fatalf("got %q want the superseded store", got)
		}
		if _, _, src := pdfScan(ctx, doc); src != pdfStoreMarker {
			t.Fatal("the superseded store was attributed to the document")
		}
	})
}

// pdfEmptyJUMB is a well-formed superbox carrying no manifest: the payload a
// decoy catalog points at to make a signed document read as unsigned.
var pdfEmptyJUMB = []byte{0, 0, 0, 8, 'j', 'u', 'm', 'b'}

// TestPDFJUMBF_AuthoritativeCatalog pins that only the cross-reference section
// the last startxref names can say which object is the catalog. Taking the last
// /Root, or the last lexical definition of an object number, lets bytes no
// reader treats as part of the document redirect it — and a decoy pointing at an
// empty superbox turns a signed manifest into an absent one, which costs no
// cryptography and reads as "no provenance" rather than as tampering.
func TestPDFJUMBF_AuthoritativeCatalog(t *testing.T) {
	store := synthJUMB([]byte("manifest store"))
	ctx := context.Background()

	genuine := newPDFDoc().
		obj(1, "<< /Type /Catalog /Pages 2 0 R /AF [3 0 R] >>").
		obj(2, "<< /Type /Pages /Kids [] /Count 0 >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, store, "").
		xrefTrailer(1)
	if got := pdfJUMBF(ctx, genuine.bytes()); !bytes.Equal(got, store) {
		t.Fatalf("genuine document: got %q want the store", got)
	}

	decoy := fmt.Sprintf("900 0 obj\n<< /Type /Catalog /AF [901 0 R] >>\nendobj\n"+
		"901 0 obj\n<< /Type /Filespec /AFRelationship /C2PA_Manifest"+
		" /EF << /F 902 0 R >> >>\nendobj\n"+
		"902 0 obj\n<< /Type /EmbeddedFile /Length %d >>\nstream\n%s\nendstream\nendobj\n",
		len(pdfEmptyJUMB), pdfEmptyJUMB)

	t.Run("trailer appended after EOF", func(t *testing.T) {
		// No cross-reference section of its own, so startxref still names the
		// genuine table and these bytes are not part of the document.
		tampered := genuine.clone().
			append(decoy + "trailer\n<< /Size 903 /Root 900 0 R >>\n").bytes()
		t.Logf("%d bytes appended", len(tampered)-len(genuine.bytes()))
		if got := pdfJUMBF(ctx, tampered); !bytes.Equal(got, store) {
			t.Fatalf("appended decoy catalog won: got %q want the genuine store", got)
		}
	})

	t.Run("startxref appended after EOF", func(t *testing.T) {
		// The decoy brings its own startxref, so the last one in the file no
		// longer names the genuine table. Taking only the last leaves the
		// document with no section that places a /Root, and the genuine store is
		// then never reached.
		tampered := genuine.clone().
			append(decoy + "trailer\n<< /Size 903 /Root 900 0 R >>\nstartxref\n0\n%%EOF\n").bytes()
		if got := pdfJUMBF(ctx, tampered); !bytes.Equal(got, store) {
			t.Fatalf("appended startxref won: got %q want the genuine store", got)
		}
	})

	t.Run("appended xref names a root it does not place", func(t *testing.T) {
		// The section parses and its trailer carries /Root, so taking a candidate on the presence of
		// /Root alone accepts it. It places nothing, so the catalog never resolves and the genuine
		// earlier startxref is never reached: a candidate has to place its root to count.
		tampered := genuine.clone().
			append(decoy).appendUnplacedXref(900).bytes()
		if got := pdfJUMBF(ctx, tampered); !bytes.Equal(got, store) {
			t.Fatalf("appended xref won: got %q want the genuine store", got)
		}
	})

	t.Run("appended xref places a root at an offset nothing sits at", func(t *testing.T) {
		// The entry is in use, so the section did place something; the offset resolves to no object.
		// A candidate has to reach the catalog it names, not merely claim a location for it.
		tampered := genuine.clone().
			append(decoy).appendMisplacedXref(900, 1).bytes()
		if got := pdfJUMBF(ctx, tampered); !bytes.Equal(got, store) {
			t.Fatalf("misplaced xref won: got %q want the genuine store", got)
		}
	})

	t.Run("phantom catalog redefining the object", func(t *testing.T) {
		// The decoy redefines object 1 rather than naming a new one, so it needs
		// no /Root of its own: the lexical "last definition wins" rule hands it
		// the document.
		tampered := genuine.clone().
			append("1 0 obj\n<< /Type /Catalog /AF [901 0 R] >>\nendobj\n" +
				decoy).bytes()
		if got := pdfJUMBF(ctx, tampered); !bytes.Equal(got, store) {
			t.Fatalf("phantom catalog won: got %q want the genuine store", got)
		}
	})
}

// xrefStream appends a real cross-reference stream over the objects written so
// far — /W [1 2 1] rows, type 1 entries carrying a two-byte offset — and a
// startxref naming it. This is what a PDF 1.5+ producer writes instead of a
// table, and without decoding it the catalog has no location.
func (d *pdfDoc) xrefStream(num, root int) *pdfDoc {
	high := num
	for n := range d.offs {
		high = max(high, n)
	}
	var rows bytes.Buffer
	for n := 0; n <= high; n++ {
		if off, ok := d.offs[n]; ok {
			rows.Write([]byte{1, byte(off >> 8), byte(off), 0})
		} else {
			rows.Write([]byte{0, 0, 0, 0})
		}
	}
	at := len(d.b)
	d.stream(num, fmt.Sprintf("/Type /XRef /Size %d /Root %d 0 R /W [1 2 1]", high+1, root),
		rows.Bytes(), "")
	return d.append(fmt.Sprintf("startxref\n%d\n%%%%EOF\n", at))
}

// TestPDFJUMBF_XrefStreamPlacesTheCatalog pins that a document using a
// cross-reference stream is protected the same way one using a table is. Without
// decoding the stream's /W rows the catalog has no location, lexical order
// decides, and the decoy appended after %%EOF wins — on the carrier most modern
// producers write.
func TestPDFJUMBF_XrefStreamPlacesTheCatalog(t *testing.T) {
	ctx := context.Background()
	store := synthJUMB([]byte("manifest store"))

	genuine := newPDFDoc().
		obj(1, "<< /Type /Catalog /Pages 2 0 R /AF [3 0 R] >>").
		obj(2, "<< /Type /Pages /Kids [] /Count 0 >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, store, "").
		xrefStream(6, 1)

	if _, got, src := pdfScan(ctx, genuine.bytes()); !bytes.Equal(got, store) ||
		src != pdfStoreCatalog {
		t.Fatalf("genuine document: got %q source %v", got, src)
	}

	tampered := genuine.clone().append(
		"1 0 obj\n<< /Type /Catalog /AF [901 0 R] >>\nendobj\n" +
			"901 0 obj\n<< /Type /Filespec /AFRelationship /C2PA_Manifest" +
			" /EF << /F 902 0 R >> >>\nendobj\n" +
			fmt.Sprintf("902 0 obj\n<< /Type /EmbeddedFile /Length %d >>\nstream\n%s\n"+
				"endstream\nendobj\n", len(pdfEmptyJUMB), pdfEmptyJUMB)).bytes()

	if _, got, src := pdfScan(ctx, tampered); !bytes.Equal(got, store) ||
		src != pdfStoreCatalog {
		t.Fatalf("decoy redirected an xref-stream document: got %q source %v", got, src)
	}
}

// TestPDFJUMBF_CompressedObjectDoesNotDisplaceAVisibleOne pins revision order.
// An object stream's contents are indexed after every visible object, and file
// order says nothing about which revision they belong to, so taking the newest
// entry outright let a stale compressed catalog beat one an incremental update
// appended in plain sight — reviving a superseded store.
func TestPDFJUMBF_CompressedObjectDoesNotDisplaceAVisibleOne(t *testing.T) {
	superseded := synthJUMB([]byte("the superseded store"))
	current := synthJUMB([]byte("the current store"))

	inner := map[int]string{
		1: "<< /Type /Catalog /Pages 2 0 R /AF [3 0 R] >>",
		3: "<< /Type /Filespec /AFRelationship /C2PA_Manifest /EF << /F 4 0 R >> >>",
	}
	var hdr, bodies string
	for _, n := range []int{1, 3} {
		hdr += fmt.Sprintf("%d %d ", n, len(bodies))
		bodies += inner[n] + " "
	}

	d := newPDFDoc()
	d.stream(5, fmt.Sprintf("/Type /ObjStm /N 2 /First %d /Filter /FlateDecode", len(hdr)),
		zlibBytes(t, []byte(hdr+bodies)), "")
	d.stream(4, pdfEmbeddedFileDict, superseded, "")
	d.append("trailer\n<< /Root 1 0 R >>\nstartxref\n0\n%%EOF\n")
	// An incremental update rewrites the catalog in plain sight.
	d.obj(1, "<< /Type /Catalog /Pages 2 0 R /AF [7 0 R] >>").
		obj(7, "<< /Type /Filespec /AFRelationship /C2PA_Manifest /EF << /F 8 0 R >> >>").
		stream(8, pdfEmbeddedFileDict, current, "").
		append("trailer\n<< /Root 1 0 R >>\nstartxref\n0\n%%EOF\n")

	if got := pdfJUMBF(context.Background(), d.bytes()); !bytes.Equal(got, current) {
		t.Fatalf("got %q want the update's store", got)
	}
}

// TestPDFJUMBF_DecoyObjectStreamsCannotDrainBudget pins that inflating an object
// stream is charged only for a payload whose objects are kept. Two 16 KiB decoys
// that expand to 8 MiB of nothing otherwise spend the whole budget and starve the
// stream carrying the real chain.
func TestPDFJUMBF_DecoyObjectStreamsCannotDrainBudget(t *testing.T) {
	store := synthJUMB([]byte("manifest store"))
	inner := map[int]string{
		1: "<< /Type /Catalog /Pages 2 0 R /AF [3 0 R] >>",
		3: "<< /Type /Filespec /AFRelationship /C2PA_Manifest /EF << /F 4 0 R >> >>",
	}
	var hdr, bodies string
	for _, n := range []int{1, 3} {
		hdr += fmt.Sprintf("%d %d ", n, len(bodies))
		bodies += inner[n] + " "
	}
	junk := zlibBytes(t, bytes.Repeat([]byte("x"), maxPDFStreamInflate))

	d := newPDFDoc()
	d.stream(10, "/Type /ObjStm /N 1 /First 4 /Filter /FlateDecode", junk, "")
	d.stream(11, "/Type /ObjStm /N 1 /First 4 /Filter /FlateDecode", junk, "")
	d.stream(5, fmt.Sprintf("/Type /ObjStm /N 2 /First %d /Filter /FlateDecode", len(hdr)),
		zlibBytes(t, []byte(hdr+bodies)), "")
	// No /Subtype, as the one real producer file available carries none, so the
	// marker fallback cannot quietly rescue this.
	d.stream(4, "/Type /EmbeddedFile", store, "")
	d.append("trailer\n<< /Root 1 0 R >>\nstartxref\n0\n%%EOF\n")

	if _, got, src := pdfScan(context.Background(), d.bytes()); !bytes.Equal(got, store) ||
		src != pdfStoreCatalog {
		t.Fatalf("decoy object streams suppressed the chain: got %d bytes source %v",
			len(got), src)
	}
}

// TestPDFJUMBF_MarkerFallback covers the documents whose pointer chain is not
// visible to a lexical scan — a catalog or file specification compressed into an
// object stream. The embedded file stream itself always is, so the extractor
// falls back to the spec's own markers on it.
func TestPDFJUMBF_MarkerFallback(t *testing.T) {
	store := synthJUMB([]byte("manifest store"))
	ctx := context.Background()

	t.Run("catalog not visible", func(t *testing.T) {
		// /Root names an object that is not in the plain object bytes.
		doc := newPDFDoc().
			obj(3, pdfC2PAFilespec).
			stream(4, pdfEmbeddedFileDict, store, "").
			trailer(1).bytes()
		if got := pdfJUMBF(ctx, doc); !bytes.Equal(got, store) {
			t.Fatalf("relationship fallback failed: got %q", got)
		}
	})
	t.Run("only the embedded file visible", func(t *testing.T) {
		doc := newPDFDoc().
			stream(4, pdfEmbeddedFileDict, store, "").
			trailer(1).bytes()
		if got := pdfJUMBF(ctx, doc); !bytes.Equal(got, store) {
			t.Fatalf("/Subtype fallback failed: got %q", got)
		}
	})
	t.Run("unmarked embedded file is not assumed", func(t *testing.T) {
		doc := newPDFDoc().
			stream(4, "/Type /EmbeddedFile /Subtype /text#2Fplain", store, "").
			trailer(1).bytes()
		if got := pdfJUMBF(ctx, doc); got != nil {
			t.Fatalf("unmarked embedded file yielded %q", got)
		}
	})
}

// pdfObjStmDoc hides the pointer chain in an object stream: the catalog and the
// file specification live inside a /Type /ObjStm, the xref stream's dictionary
// names /Root, and only the manifest stream is plainly visible. It carries no
// /Subtype, as the one real producer file available does not.
func pdfObjStmDoc(t *testing.T, store []byte) []byte {
	t.Helper()
	inner := map[int]string{
		1: "<< /Type /Catalog /Pages 2 0 R /AF [3 0 R] >>",
		3: "<< /Type /Filespec /F (c2pa.c2pa) /AFRelationship /C2PA_Manifest" +
			" /EF << /F 4 0 R >> >>",
	}
	var hdr, bodies string
	for _, num := range []int{1, 3} {
		hdr += fmt.Sprintf("%d %d ", num, len(bodies))
		bodies += inner[num] + " "
	}

	d := newPDFDoc()
	d.stream(5, fmt.Sprintf("/Type /ObjStm /N 2 /First %d /Filter /FlateDecode", len(hdr)),
		zlibBytes(t, []byte(hdr+bodies)), "")
	d.stream(4, "/Type /EmbeddedFile", store, "")
	xref := len(d.bytes())
	d.stream(6, "/Type /XRef /Size 7 /Root 1 0 R /W [1 2 1]", []byte{0}, "")
	return d.append(fmt.Sprintf("startxref\n%d\n%%%%EOF\n", xref)).bytes()
}

// TestPDFJUMBF_ObjectStreamChain pins that a chain compressed into an object
// stream is still followed. §7.5.7 forbids a stream object inside an object
// stream, but the §A.4.1 markers live on the file specification dictionary,
// which it permits — so the manifest bytes being visible does not make the store
// identifiable, and a conforming document like this one yielded nothing.
func TestPDFJUMBF_ObjectStreamChain(t *testing.T) {
	store := synthJUMB([]byte("manifest store"))
	doc := pdfObjStmDoc(t, store)
	if bytes.Contains(doc, []byte(pdfC2PARelationship)) {
		t.Fatal("the relationship marker is still visible in the plain bytes")
	}
	if got := pdfJUMBF(context.Background(), doc); !bytes.Equal(got, store) {
		t.Fatalf("object-stream chain not recovered: got %d bytes, want %d", len(got), len(store))
	}
}

// TestPDFJUMBF_SentinelBytesInPayload pins that a store holding the keywords
// that delimit PDF objects survives. The payload is arbitrary binary — CBOR, a
// thumbnail — so it can carry `endobj`, and ending the object body at the first
// one loses the manifest. Signing a document whose title holds those six bytes
// would otherwise be enough to make it read as unsigned.
func TestPDFJUMBF_SentinelBytesInPayload(t *testing.T) {
	ctx := context.Background()
	for _, sentinel := range []string{"endobj", "endstream", "\nendobj\nendstream\n"} {
		for _, compress := range []bool{false, true} {
			t.Run(fmt.Sprintf("%q/compressed=%v", sentinel, compress), func(t *testing.T) {
				store := synthJUMB([]byte("a title " + sentinel + " and more"))
				got := pdfJUMBF(ctx, synthPDF(t, store, compress))
				if !bytes.Equal(got, store) {
					t.Fatalf("got %d bytes, want %d", len(got), len(store))
				}
			})
		}
	}
}

// TestPDFJUMBF_RepairStaysInsideTheObject pins that re-cutting cannot reach past the object being
// re-cut. The keyword search runs forward from the body start, so a small dictionary sitting just
// before a stream object can find that stream's `stream` keyword and its indirect /Length and be
// re-cut through it — handing the document a store it does not associate as its own.
func TestPDFJUMBF_RepairStaysInsideTheObject(t *testing.T) {
	store := synthJUMB([]byte("an attachment's manifest"))
	doc := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
		// The embedded file the catalog's specification names does not exist, so the §A.4.2.1 chain
		// resolves to nothing and no store is the document's.
		obj(3, "<< /Type /Filespec /F (c2pa.c2pa) /UF (c2pa.c2pa) "+
			"/AFRelationship /C2PA_Manifest /EF << /F 99 0 R >> >>").
		stream(4, pdfEmbeddedFileDict, store, "9 0 R").
		obj(9, fmt.Sprint(len(store))).
		trailer(1).bytes()

	_, got, src := pdfScan(context.Background(), doc)
	if src == pdfStoreCatalog {
		t.Fatalf("an unrelated stream was attributed to the document: %q", got)
	}
	// Still surfaced by the markers, which is right: it is a store the file carries.
	if !bytes.Equal(got, store) || src != pdfStoreMarker {
		t.Fatalf("src=%v got %d bytes, want the store by marker", src, len(got))
	}
}

// TestPDFJUMBF_RepairDropsPhantomsFromThePayload pins that re-cutting an object also un-indexes what
// was read out of its payload. Until the length resolves the object ends at the payload's first
// `endobj`, so header-shaped bytes after that point are indexed as real objects; one of them naming
// the stream's own number shadows it, and the store becomes unreachable.
func TestPDFJUMBF_RepairDropsPhantomsFromThePayload(t *testing.T) {
	store := synthJUMB([]byte("a title \n4 0 obj\njunk\nendobj\n and more"))
	doc := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, store, "9 0 R").
		obj(9, fmt.Sprint(len(store))).
		trailer(1).bytes()

	// Asserted through the source, not just the bytes: the phantom breaks the §A.4.2.1 chain, and the
	// markers then find the same store with nothing able to say it is the document's. Reporting the
	// document's own manifest as unattributed is the whole distinction Attribution exists to carry.
	_, got, src := pdfScan(context.Background(), doc)
	if !bytes.Equal(got, store) {
		t.Fatalf("got %d bytes, want %d", len(got), len(store))
	}
	if src != pdfStoreCatalog {
		t.Fatalf("src = %v, want the catalog to still place the store", src)
	}
}

// TestPDFJUMBF_PayloadPhantomCannotBlockItsOwnCleanup pins the deadlock between the two halves of
// the repair. The length object is resolved before any phantom is dropped, so a payload spelling
// that object's own header shadows the real definition: the length does not resolve, the object is
// not re-cut, no payload extent is recorded, and the phantom is never dropped either.
func TestPDFJUMBF_PayloadPhantomCannotBlockItsOwnCleanup(t *testing.T) {
	store := synthJUMB([]byte("a title \n9 0 obj\n7\nendobj\n and more"))
	doc := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
		obj(3, pdfC2PAFilespec).
		// The length object is written before the stream, which is what lets the payload's copy of
		// its header win on the lexical "last definition of a number" rule.
		obj(9, fmt.Sprint(len(store))).
		stream(4, pdfEmbeddedFileDict, store, "9 0 R").
		trailer(1).bytes()

	_, got, src := pdfScan(context.Background(), doc)
	if !bytes.Equal(got, store) {
		t.Fatalf("got %d bytes, want %d", len(got), len(store))
	}
	if src != pdfStoreCatalog {
		t.Fatalf("src = %v, want the catalog to still place the store", src)
	}
}

// TestPDFJUMBF_PayloadPhantomCannotTruncateTheStream pins that a fabricated length cannot cut the
// object short. Trying several definitions needs more than "the value lands on `endstream`": a
// payload can carry both a phantom length-object definition and an `endstream` for it to point at,
// and being earlier in the file it is tried before the real definition. What gives it away is that
// its own header sits inside the extent it claims, which no real length object can.
func TestPDFJUMBF_PayloadPhantomCannotTruncateTheStream(t *testing.T) {
	// The payload carries three things: a phantom definition of the length object, an `endstream` for
	// its value to land on, and an `endobj` past that for the re-cut body to stop at. %%%% is
	// replaced in place once the offset is known, so every offset stays put.
	inner := append([]byte("\n9 0 obj\n%%%%\nendobj\n"), bytes.Repeat([]byte("A"), 60)...)
	inner = append(inner, "endstream\nendobj\n"...)
	inner = append(inner, bytes.Repeat([]byte("B"), 60)...)
	store := synthJUMB(inner)

	at := bytes.Index(store, []byte("endstream"))
	if at < 0 || at > 9999 {
		t.Fatalf("internal endstream at %d, unusable", at)
	}
	store = bytes.Replace(store, []byte("%%%%"), []byte(fmt.Sprintf("%04d", at)), 1)

	doc := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, store, "9 0 R").
		obj(9, fmt.Sprint(len(store))).
		trailer(1).bytes()

	got := pdfJUMBF(context.Background(), doc)
	if !bytes.Equal(got, store) {
		t.Fatalf("got %d bytes, want the whole %d-byte store", len(got), len(store))
	}
}

// TestPDFJUMBF_IndirectLengthWithSentinelInPayload combines the two things the
// scanner survives one at a time. An indirect /Length cannot be resolved on the
// forward pass, so the object falls back to the first `endobj`; a store is
// arbitrary binary and can spell one. The length object is written after the
// stream, which is what makes the forward pass unable to see it and what a
// producer emits.
func TestPDFJUMBF_IndirectLengthWithSentinelInPayload(t *testing.T) {
	ctx := context.Background()
	for _, sentinel := range []string{"endobj", "\nendobj\nendstream\n"} {
		t.Run(sentinel, func(t *testing.T) {
			store := synthJUMB([]byte("a title " + sentinel + " and more"))
			doc := newPDFDoc().
				obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
				obj(3, pdfC2PAFilespec).
				stream(4, pdfEmbeddedFileDict, store, "9 0 R").
				obj(9, fmt.Sprint(len(store))).
				trailer(1).bytes()

			if got := pdfJUMBF(ctx, doc); !bytes.Equal(got, store) {
				t.Fatalf("got %d bytes, want %d", len(got), len(store))
			}
		})
	}
}

// pdfWithAttachmentManifest builds a document whose catalog associates a plain
// attachment, while a second embedded file carries a C2PA manifest that nothing
// in the catalog points at — what §A.4.3 describes, and what an attachment
// carrying its own provenance looks like.
func pdfWithAttachmentManifest(store []byte) []byte {
	return newPDFDoc().
		obj(1, "<< /Type /Catalog /Pages 2 0 R /AF [3 0 R] >>").
		obj(2, "<< /Type /Pages /Kids [] /Count 0 >>").
		obj(3, "<< /Type /Filespec /F (notes.txt) /AFRelationship /Supplement >>").
		obj(7, "<< /Type /Filespec /F (image.jpg) /AFRelationship /C2PA_Manifest"+
			" /EF << /F 8 0 R >> >>").
		stream(8, pdfEmbeddedFileDict, store, "").
		xrefTrailer(1).bytes()
}

// TestReadPDF_Attribution pins what a manifest is a claim about. §A.4.3 gives a
// manifest describing an embedded file the identical /AFRelationship, and
// §A.4.2.1 puts the document-level specification in the EmbeddedFiles name tree
// as well, so the catalog's /AF reference is the only discriminator. Reporting
// the store without saying which it was leaves a caller no way to tell.
func TestReadPDF_Attribution(t *testing.T) {
	ctx := context.Background()
	fixture, err := os.ReadFile("testdata/c2pa_signed.jpg")
	if err != nil {
		t.Fatal(err)
	}
	store := extractJUMBF(ctx, JPEG, fixture)

	t.Run("the catalog associates it", func(t *testing.T) {
		got := Read(ctx, PDF, bytes.NewReader(synthPDF(t, store, false)))
		if !got.Present {
			t.Fatal("no manifest read")
		}
		if got.Attribution != AttributionAsset {
			t.Errorf("Attribution = %q, want %q", got.Attribution, AttributionAsset)
		}
	})

	t.Run("nothing associates it", func(t *testing.T) {
		// Still surfaced: an attachment carrying a signed, generated file is a
		// finding. What must not happen is reporting its signer as the
		// document's, which only the attribution can prevent.
		got := Read(ctx, PDF, bytes.NewReader(pdfWithAttachmentManifest(store)))
		if !got.Present {
			t.Fatal("an unattributed manifest was dropped, leaving no signal at all")
		}
		if got.Attribution != AttributionUnknown {
			t.Errorf("Attribution = %q, want %q", got.Attribution, AttributionUnknown)
		}
		if got.SignedBy == "" {
			t.Error("SignedBy is empty, so the caller cannot see whose manifest it is")
		}
	})

	t.Run("a carrier with nowhere to hide one", func(t *testing.T) {
		got := Read(ctx, JPEG, bytes.NewReader(fixture))
		if !got.Present {
			t.Fatal("fixture has no manifest")
		}
		if got.Attribution != AttributionAsset {
			t.Errorf("Attribution = %q, want %q", got.Attribution, AttributionAsset)
		}
	})

	t.Run("no manifest attributes nothing", func(t *testing.T) {
		got := Read(ctx, PDF, bytes.NewReader([]byte("%PDF-1.7\nnothing here\n")))
		if got.Present || got.Attribution != AttributionNone {
			t.Errorf("got %+v, want a zero Info", got)
		}
	})
}

// TestValidatePDF_MarkerSourcedStoreIsReported pins that a store found by the
// markers, with no catalog to attribute it, is reported as such — the result
// could not otherwise express "found a manifest, cannot prove it is this
// document's".
func TestValidatePDF_MarkerSourcedStoreIsReported(t *testing.T) {
	pool, data := fixtureSigningPool(t)
	ctx := context.Background()
	// No catalog is visible, so the markers are the only route left.
	doc := newPDFDoc().
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, extractJUMBF(ctx, JPEG, data), "").
		trailer(1).bytes()

	r := Validate(ctx, PDF, bytes.NewReader(doc), WithSigningTrust(pool))
	if !r.Has(StatusClaimSignatureValidated) {
		t.Fatalf("signature not validated through the fallback: %v", codes(r))
	}
	for _, s := range r.Statuses {
		if s.Code == StatusUnsupported && strings.Contains(s.Explanation, "markers") {
			return
		}
	}
	t.Errorf("no status says the store was identified by its markers: %+v", r.Statuses)
}

// TestPDFJUMBF_Malformed feeds every truncation of a good document plus a set
// of hand-broken ones. Nothing may panic, hang, or invent a manifest.
func TestPDFJUMBF_Malformed(t *testing.T) {
	ctx := context.Background()
	store := synthJUMB([]byte("manifest store"))
	doc := synthPDF(t, store, true)
	// A returned store must be the whole superbox: looksLikeJUMBF only accepts
	// bytes whose declared length is present, so a truncation either finds all
	// of it or nothing. Asserting "not a 0x00 prefix" admitted every possible
	// return, since every superbox under 16 MiB opens with a 0x00 length byte.
	for n := 0; n < len(doc); n++ {
		if got := pdfJUMBF(ctx, doc[:n]); got != nil && !bytes.Equal(got, store) {
			t.Fatalf("truncated to %d bytes yielded %q", n, got)
		}
	}

	for name, broken := range map[string][]byte{
		"header only":          []byte("%PDF-1.7\n"),
		"unterminated object":  []byte("%PDF-1.7\n1 0 obj\n<< /Type /Catalog /AF [3 0 R] >>"),
		"stream never ends":    []byte("%PDF-1.7\n4 0 obj\n<< /Subtype /application#2Fc2pa /Length 8 >>\nstream\n"),
		"self-referential AF":  []byte("%PDF-1.7\n1 0 obj\n<< /Type /Catalog /AF [1 0 R] >>\nendobj\ntrailer\n<< /Root 1 0 R >>"),
		"absurd object number": []byte("%PDF-1.7\n99999999999999999999 0 obj\n<< /AFRelationship /C2PA_Manifest >>\nendobj\n"),
		"garbage flate":        []byte("%PDF-1.7\n4 0 obj\n<< /Subtype /application#2Fc2pa /Filter /FlateDecode /Length 4 >>\nstream\n\xff\xff\xff\xff\nendstream\nendobj\n"),
	} {
		if got := pdfJUMBF(ctx, broken); got != nil {
			t.Errorf("%s: yielded %q", name, got)
		}
	}
}

// TestPDFJUMBF_PathologicalCost pins the bounds that keep the scan linear. An
// object header with no `endobj` runs its body to the end of the file, and a
// repeated marker offers a fresh candidate stream per copy; unbounded, either
// would cost a full scan per object. The test only has to finish.
func TestPDFJUMBF_PathologicalCost(t *testing.T) {
	ctx := context.Background()

	t.Run("headers with no endobj", func(t *testing.T) {
		doc := append([]byte("%PDF-1.7\n"), bytes.Repeat([]byte("1 0 obj\n"), 100_000)...)
		doc = append(doc, bytes.Repeat([]byte{0xAB}, 1<<20)...)
		if got := pdfJUMBF(ctx, doc); got != nil {
			t.Fatalf("yielded %d bytes", len(got))
		}
	})
	t.Run("repeated marker, no endstream", func(t *testing.T) {
		doc := append([]byte("%PDF-1.7\n"),
			bytes.Repeat([]byte("1 0 obj\n<< /Subtype /application#2Fc2pa /Length 99999 >>\nstream\n"), 50_000)...)
		if got := pdfJUMBF(ctx, doc); got != nil {
			t.Fatalf("yielded %d bytes", len(got))
		}
	})

	// Every indirect-length stream resolves, so each contributes a payload extent to exclude from the
	// index. Checking each extent against every object is quadratic, and this document fits well
	// under Read's 16 MiB cap: 200k of them measured 13.5s that way against 583ms for one merged
	// walk. The ceiling is calibrated on the merged walk under -race, which is what CI runs.
	t.Run("many indirect-length streams", func(t *testing.T) {
		var b bytes.Buffer
		b.WriteString("%PDF-1.7\n1 0 obj\n<< /Type /Catalog >>\nendobj\n2 0 obj\n0\nendobj\n")
		for i := 0; i < 200_000; i++ {
			fmt.Fprintf(&b, "%d 0 obj\n<< /Length 2 0 R >>\nstream\n\nendstream\nendobj\n", 10+i)
		}
		b.WriteString("trailer\n<< /Root 1 0 R >>\nstartxref\n0\n%%EOF\n")

		start := time.Now()
		if got := pdfJUMBF(ctx, b.Bytes()); got != nil {
			t.Fatalf("yielded %d bytes", len(got))
		}
		if elapsed := time.Since(start); elapsed > 8*time.Second {
			t.Fatalf("took %v, want the payload-extent walk to stay linear", elapsed)
		}
	})

	// Every stream names the same length object, and every definition of it is a fabrication that
	// never parses. Trying them all is N attempts per stream and N² overall.
	// maxPDFLengthCandidates is what bounds it: 0.39s under -race against 12.9s unbounded.
	t.Run("one length object defined many times", func(t *testing.T) {
		var b bytes.Buffer
		b.WriteString("%PDF-1.7\n1 0 obj\n<< /Type /Catalog >>\nendobj\n")
		for range 60_000 {
			b.WriteString("2 0 obj\nnotanumber\nendobj\n")
		}
		for i := range 60_000 {
			fmt.Fprintf(&b, "%d 0 obj\n<< /Length 2 0 R >>\nstream\n\nendstream\nendobj\n", 10+i)
		}
		b.WriteString("trailer\n<< /Root 1 0 R >>\nstartxref\n0\n%%EOF\n")

		start := time.Now()
		if got := pdfJUMBF(ctx, b.Bytes()); got != nil {
			t.Fatalf("yielded %d bytes", len(got))
		}
		if elapsed := time.Since(start); elapsed > 4*time.Second {
			t.Fatalf("took %v, want the candidate search to stay bounded", elapsed)
		}
	})
}

// pdfOpenArrayDoc builds kib kibibytes of a repeated token behind one real
// object, so the object index is non-empty and /Root resolution actually runs.
func pdfOpenArrayDoc(kib int, tok string) []byte {
	doc := append([]byte("%PDF-1.7\n"), "1 0 obj\n<< /Type /Catalog >>\nendobj\n"...)
	return append(doc, bytes.Repeat([]byte(tok), kib*1024/len(tok))...)
}

// TestPDFJUMBF_UnterminatedArrayCost pins the bounds behind the `/Root[` shape.
// `[` is a delimiter, so the name token matches and opens an array; searching for
// the `]` that never arrives cost the rest of the buffer, once per /Root, over
// every /Root — quadratic, and minutes at Read's 16 MiB cap. The window bound and
// the context check are asserted directly, since a wall-clock ceiling tight
// enough to catch the defect also fails under -race on a shared runner.
func TestPDFJUMBF_UnterminatedArrayCost(t *testing.T) {
	t.Run("array window is bounded", func(t *testing.T) {
		b := append([]byte("["), bytes.Repeat([]byte("0 0 R "), 1<<16)...)
		if got, want := pdfArrayEnd(b, 1), 1+maxPDFDictScan; got != want {
			t.Fatalf("pdfArrayEnd = %d, want the window bound %d", got, want)
		}
		// A closing bracket inside the window is still what ends the array.
		b[1+64] = ']'
		if got, want := pdfArrayEnd(b, 1), 1+64; got != want {
			t.Fatalf("pdfArrayEnd = %d, want the bracket at %d", got, want)
		}
	})

	t.Run("root scan honours the context", func(t *testing.T) {
		// The trailer's /Root resolves, so without the check the scan finds it.
		doc := append(pdfOpenArrayDoc(64, "/Root["), "trailer\n<< /Root 1 0 R >>\n"...)
		if root, ok := pdfRootLexical(context.Background(), doc); !ok || root != 1 {
			t.Fatalf("pdfRootLexical = (%d, %v), want (1, true) without a deadline", root, ok)
		}
		ctx, cancel := context.WithCancel(context.Background())
		cancel()
		if root, ok := pdfRootLexical(ctx, doc); ok {
			t.Fatalf("a cancelled context still resolved /Root to %d", root)
		}
	})

	// A smoke guard, not the pin: generous enough for -race on a shared runner,
	// where the bounded scan of this document has been seen to take ~0.6s.
	t.Run("whole scan finishes", func(t *testing.T) {
		doc := pdfOpenArrayDoc(1024, "/Root[")
		start := time.Now()
		if got := pdfJUMBF(context.Background(), doc); got != nil {
			t.Fatalf("yielded %d bytes", len(got))
		}
		if d := time.Since(start); d > 5*time.Second {
			t.Fatalf("1 MiB of unterminated arrays took %v", d)
		}
	})
}

// TestPDFJUMBF_CompressionBomb pins that inflation is capped: a stream that
// expands far past maxPDFInflate returns rather than exhausting memory.
func TestPDFJUMBF_CompressionBomb(t *testing.T) {
	bomb := zlibBytes(t, make([]byte, maxPDFInflate+(64<<20)))
	doc := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict+" /Filter /FlateDecode", bomb, "").
		trailer(1).bytes()
	if got := pdfJUMBF(context.Background(), doc); got != nil {
		t.Fatalf("compression bomb yielded %d bytes", len(got))
	}
}

// TestPDFJUMBF_DecoyCannotDrainBudget pins that one decoy stream cannot spend
// the whole decompression budget and suppress the real manifest behind it.
// Charging a single shared pool for a candidate that produced no store turns a
// 16 KiB stream of zeros into a suppression primitive, and the /AF array is
// attacker-ordered, so the decoy goes first.
func TestPDFJUMBF_DecoyCannotDrainBudget(t *testing.T) {
	store := synthJUMB([]byte("manifest store"))
	doc := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [100 0 R 3 0 R] >>").
		obj(100, "<< /Type /Filespec /AFRelationship /C2PA_Manifest /EF << /F 101 0 R >> >>").
		stream(101, pdfEmbeddedFileDict+" /Filter /FlateDecode",
			zlibBytes(t, make([]byte, maxPDFInflate)), "").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict+" /Filter /FlateDecode", zlibBytes(t, store), "").
		trailer(1).bytes()
	t.Logf("whole document is %d bytes", len(doc))
	if got := pdfJUMBF(context.Background(), doc); !bytes.Equal(got, store) {
		t.Fatalf("decoy suppressed the real store: got %d bytes, want %d", len(got), len(store))
	}
}

// --- end to end --------------------------------------------------------------

// TestReadPDF_RealManifest carries the JPEG fixture's own manifest store in a
// synthetic PDF and reads it back, proving the PDF carrier feeds the same
// parser: the surfaced Info must be what the JPEG yields.
func TestReadPDF_RealManifest(t *testing.T) {
	data, err := os.ReadFile("testdata/c2pa_signed.jpg")
	if err != nil {
		t.Fatal(err)
	}
	ctx := context.Background()
	want := Read(ctx, JPEG, bytes.NewReader(data))
	if !want.Present {
		t.Fatal("fixture has no manifest")
	}
	doc := synthPDF(t, extractJUMBF(ctx, JPEG, data), true)
	if got := Read(ctx, PDF, bytes.NewReader(doc)); got != want {
		t.Fatalf("Read(PDF) = %+v\nwant %+v", got, want)
	}
}

// TestValidatePDF_ProducerShapes validates a generated PDF whose carrier uses
// the four shapes an observed producer emits and the corpus's own PDF case does
// not — each on a different branch of the scan: the generation number in the
// object header and in /Root, /Type spelled /FileSpec, a /Subtype read by
// pdfText's literal-string branch rather than as a name, and a manifest that
// only the incremental update section associates.
func TestValidatePDF_ProducerShapes(t *testing.T) {
	spec := func(sb *signerBundle) manifestSpec {
		return manifestSpec{signer: sb, assertions: []assertionSpec{markerAssertion()}}
	}

	t.Run("catalog chain", func(t *testing.T) {
		sb := newCorpusSigner(t, cose.AlgorithmES256)
		asset := buildFramedAsset(t, pdfProducerFraming(true), spec(sb))
		for shape, want := range map[string]string{
			"catalog at generation 1": "/Root 5 1 R",
			"capital-S file spec":     "/Type /FileSpec",
			"literal-string subtype":  "/Subtype (application/c2pa)",
			"incremental update":      "/Prev ",
		} {
			if !bytes.Contains(asset, []byte(want)) {
				t.Fatalf("%s: asset does not carry %q", shape, want)
			}
		}
		assertPDFProducerValid(t, asset, sb)
	})

	// The chain resolving is what keeps /Subtype off the path above, so the
	// literal-string branch only carries a document whose chain is compressed
	// out of sight.
	t.Run("literal subtype alone", func(t *testing.T) {
		sb := newCorpusSigner(t, cose.AlgorithmES256)
		ctx := context.Background()
		asset := buildFramedAsset(t, pdfProducerFraming(false), spec(sb))
		if bytes.Contains(asset, []byte(pdfC2PARelationship)) {
			t.Fatal("asset still carries the relationship marker")
		}
		if _, _, src := pdfScan(ctx, asset); src != pdfStoreMarker {
			t.Fatal("the catalog still associates a store, so /Subtype is not the route")
		}
		assertPDFProducerValid(t, asset, sb)
	})
}

func assertPDFProducerValid(t *testing.T, asset []byte, sb *signerBundle) {
	t.Helper()
	res := runCorpus(t, PDF, asset, sb)
	if !res.Valid {
		t.Fatalf("expected valid, got %v", codes(res))
	}
	for _, want := range []StatusCode{
		StatusClaimSignatureValidated,
		StatusSigningCredentialTrusted,
		StatusAssertionHashedURIMatch,
		StatusAssertionDataHashMatch,
	} {
		if !res.Has(want) {
			t.Errorf("missing %s; got %v", want, codes(res))
		}
	}
}

// TestValidatePDF_ReportsUnevaluatedStores pins that a document signed twice
// says so: §A.4.2.1 asks a consumer to process every update section's store as
// one, and only the active one is evaluated here.
func TestValidatePDF_ReportsUnevaluatedStores(t *testing.T) {
	pool, data := fixtureSigningPool(t)
	ctx := context.Background()
	store := extractJUMBF(ctx, JPEG, data)

	one := synthPDF(t, store, false)
	if got := pdfTallyStores(ctx, one, indexPDFObjects(ctx, one)); got.total != 1 {
		t.Fatalf("single-store document counted %d stores", got.total)
	}
	two := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, store, "").
		trailer(1).
		obj(1, "<< /Type /Catalog /AF [5 0 R] >>").
		obj(5, "<< /AFRelationship /C2PA_Manifest /EF << /F 6 0 R >> >>").
		stream(6, pdfEmbeddedFileDict, store, "").
		trailer(1).bytes()
	// Two sections, one store each: §A.4.2.1's unmerged case, not §15.5.2.2's
	// invalid one.
	got := pdfTallyStores(ctx, two, indexPDFObjects(ctx, two))
	if got.total != 2 || got.perSection != 1 {
		t.Fatalf("re-signed document tallied %+v, want total 2 across one-store sections", got)
	}

	r := Validate(ctx, PDF, bytes.NewReader(two), WithSigningTrust(pool))
	if !r.Has(StatusUnsupported) {
		t.Errorf("expected an informational status for the store not evaluated: %+v", r.Statuses)
	}
	if !r.Has(StatusClaimSignatureValidated) {
		t.Errorf("active manifest's signature not validated: %+v", r.Statuses)
	}
}

// TestValidatePDF_MultipleStoresInOneSection pins §15.5.2.2: multiple manifest
// stores in a single update section "shall all be considered as invalid and the
// validation should treat this as if no manifests were located". Recording that
// informationally left Valid true and still surfaced one of them.
func TestValidatePDF_MultipleStoresInOneSection(t *testing.T) {
	pool, data := fixtureSigningPool(t)
	ctx := context.Background()
	store := extractJUMBF(ctx, JPEG, data)

	doc := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [3 0 R 5 0 R] >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, store, "").
		obj(5, "<< /Type /Filespec /AFRelationship /C2PA_Manifest /EF << /F 6 0 R >> >>").
		stream(6, pdfEmbeddedFileDict, store, "").
		xrefTrailer(1).bytes()

	r := Validate(ctx, PDF, bytes.NewReader(doc), WithSigningTrust(pool))
	if r.Valid {
		t.Errorf("two stores in one update section validated: %v", codes(r))
	}
	if !r.Has(StatusClaimMissing) {
		t.Errorf("expected %s, treating it as if no manifest were located: %v",
			StatusClaimMissing, codes(r))
	}
	if r.Has(StatusClaimSignatureValidated) {
		t.Errorf("a store was still surfaced and verified: %v", codes(r))
	}
}

// TestValidatePDF_StoreCountSeesMarkedStores pins that the counter considers the
// same candidates the extractor would. Counting only file specifications whose
// /AFRelationship is C2PA_Manifest reported 0 for /Subtype-only stores, so the
// signal went silent exactly where the extractor is least sure of itself.
func TestValidatePDF_StoreCountSeesMarkedStores(t *testing.T) {
	pool, data := fixtureSigningPool(t)
	ctx := context.Background()
	store := extractJUMBF(ctx, JPEG, data)

	// No catalog is visible and neither stream carries a relationship, so
	// /Subtype is all there is to go on — and there are two of them.
	doc := newPDFDoc().
		stream(4, pdfEmbeddedFileDict, store, "").
		stream(6, pdfEmbeddedFileDict, store, "").
		trailer(1).bytes()

	r := Validate(ctx, PDF, bytes.NewReader(doc), WithSigningTrust(pool))
	for _, s := range r.Statuses {
		if s.Code == StatusUnsupported && strings.Contains(s.Explanation, "not evaluated") {
			return
		}
	}
	t.Errorf("two /Subtype-only stores reported none unevaluated: %+v", r.Statuses)
}

// TestValidatePDF_AttachmentIsNotASecondStore pins the symmetric case: an
// embedded file carrying its own object-level manifest (§A.4.3) is associated
// from the object it describes, not from a catalog, so it is not a second store
// of this document and must not raise a status.
func TestValidatePDF_AttachmentIsNotASecondStore(t *testing.T) {
	pool, data := fixtureSigningPool(t)
	ctx := context.Background()
	store := extractJUMBF(ctx, JPEG, data)

	doc := newPDFDoc().
		obj(1, "<< /Type /Catalog /AF [3 0 R] >>").
		obj(3, pdfC2PAFilespec).
		stream(4, pdfEmbeddedFileDict, store, "").
		obj(7, "<< /Type /Filespec /F (image.jpg) /AFRelationship /C2PA_Manifest"+
			" /EF << /F 8 0 R >> >>").
		stream(8, pdfEmbeddedFileDict, store, "").
		xrefTrailer(1).bytes()

	r := Validate(ctx, PDF, bytes.NewReader(doc), WithSigningTrust(pool))
	if !r.Has(StatusClaimSignatureValidated) {
		t.Fatalf("the document's own store was not evaluated: %v", codes(r))
	}
	for _, s := range r.Statuses {
		if s.Code == StatusUnsupported && strings.Contains(s.Explanation, "not evaluated") {
			t.Errorf("an attachment's manifest counted as a second store: %q", s.Explanation)
		}
	}
}

// pdfTwoSectionFraming puts a constant store in the base section and the signed
// one in an incremental update, so the document carries a store this extractor
// does not evaluate while the active manifest is still the signed one. The base
// section's bytes never change, which keeps the exclusion fixpoint stable.
func pdfTwoSectionFraming(store []byte) (asset []byte, exclStart, exclLen int) {
	earlier := synthJUMB([]byte("an earlier update section's store"))
	asset = append(asset, "%PDF-1.7\n"...)
	asset = append(asset, "1 0 obj\n<< /Type /Catalog /AF [3 0 R] >>\nendobj\n"...)
	asset = append(asset, "3 0 obj\n<< /Type /Filespec /AFRelationship /C2PA_Manifest"+
		" /EF << /F 4 0 R >> >>\nendobj\n"...)
	asset = append(asset, fmt.Sprintf("4 0 obj\n<< /Type /EmbeddedFile /Length %d >>\nstream\n",
		len(earlier))...)
	asset = append(asset, earlier...)
	asset = append(asset, "\nendstream\nendobj\ntrailer\n<< /Root 1 0 R >>\nstartxref\n0\n%%EOF\n"...)

	asset = append(asset, "1 0 obj\n<< /Type /Catalog /AF [5 0 R] >>\nendobj\n"...)
	asset = append(asset, "5 0 obj\n<< /Type /Filespec /AFRelationship /C2PA_Manifest"+
		" /EF << /F 6 0 R >> >>\nendobj\n"...)
	asset = append(asset, fmt.Sprintf("6 0 obj\n<< /Type /EmbeddedFile /Length %d >>\nstream\n",
		len(store))...)
	exclStart = len(asset)
	asset = append(asset, store...)
	exclLen = len(asset) - exclStart
	asset = append(asset, "\nendstream\nendobj\ntrailer\n<< /Root 1 0 R >>\nstartxref\n0\n%%EOF\n"...)
	return asset, exclStart, exclLen
}

// TestValidatePDF_CrossStoreIngredientIsNotAMismatch pins that an ingredient
// naming a manifest in an update section this extractor did not evaluate is not
// reported as a mismatch. §A.4.2.1 permits the reference and asks a consumer to
// process every store as one; only the active store is parsed here, so an absent
// manifest is unproven, not wrong.
func TestValidatePDF_CrossStoreIngredientIsNotAMismatch(t *testing.T) {
	sb := newCorpusSigner(t, cose.AlgorithmES256)
	asset := buildFramedAsset(t, pdfTwoSectionFraming, manifestSpec{
		signer: sb,
		assertions: []assertionSpec{
			markerAssertion(),
			{label: "c2pa.ingredient", raw: ingredientAssertion(t, "urn:in-an-earlier-section").data},
		},
	})

	ctx := context.Background()
	tally := pdfTallyStores(ctx, asset, indexPDFObjects(ctx, asset))
	if tally.total != 2 {
		t.Fatalf("framing did not produce two stores: %+v", tally)
	}

	res := runCorpus(t, PDF, asset, sb)
	if res.Has(StatusIngredientManifestMismatch) {
		t.Errorf("cross-store ingredient reported as a mismatch: %v", codes(res))
	}
	if !res.Valid {
		t.Errorf("expected valid, got %v", codes(res))
	}
}

// TestValidatePDF_VerifiesSignature runs the full validator over a PDF carrying
// the fixture's manifest. The hard binding legitimately mismatches — the
// fixture's c2pa.hash.data exclusions describe the JPEG it was signed over, not
// this document — so the assertion is that the signature step ran and passed.
func TestValidatePDF_VerifiesSignature(t *testing.T) {
	pool, data := fixtureSigningPool(t)
	ctx := context.Background()
	doc := synthPDF(t, extractJUMBF(ctx, JPEG, data), true)

	r := Validate(ctx, PDF, bytes.NewReader(doc),
		WithSigningTrust(pool), WithTimestampTrust(fixtureTimestampPool(t)))
	if !r.Has(StatusClaimSignatureValidated) {
		t.Fatalf("signature not validated through the PDF carrier: %+v", r.Statuses)
	}
	if r.Info.Title != "CA.jpg" {
		t.Errorf("Info.Title = %q want CA.jpg", r.Info.Title)
	}
	if !r.Has(StatusAssertionDataHashMismatch) {
		t.Errorf("expected the fixture's data hash to mismatch in a PDF: %+v", r.Statuses)
	}
}

// buildUnterminatedStreams produces n stream objects that each carry an
// indirect /Length and never close with `endobj` — the shape that makes the
// repair pass re-scan to end of file once per object.
func buildUnterminatedStreams(n int) []byte {
	var b bytes.Buffer
	b.WriteString("%PDF-1.7\n")
	b.WriteString("1 0 obj\n5\nendobj\n")
	for i := range n {
		fmt.Fprintf(&b, "%d 0 obj\n<< /Length 1 0 R >>\nstream\nAAAAA\nendstream\n", i+10)
	}
	b.WriteString("trailer\n<< /Root 99 0 R >>\nstartxref\n0\n%%EOF\n")
	return b.Bytes()
}

// TestPDFEndObjIsBounded pins the property directly, without depending on a
// clock. pdfEndObj is called once per repaired object, so an unbounded search
// costs a full pass over the input each time.
func TestPDFEndObjIsBounded(t *testing.T) {
	data := bytes.Repeat([]byte("A"), 4*maxPDFEndObjScan) // no `endobj` anywhere
	if got := pdfEndObj(data, 0); got > maxPDFEndObjScan {
		t.Errorf("pdfEndObj scanned to %d with no keyword present; must stop at %d", got, maxPDFEndObjScan)
	}
	// It must still find a keyword that is genuinely inside the window, which is
	// where every conforming document puts it.
	withKeyword := append(bytes.Repeat([]byte("A"), 100), "endobj"...)
	if got := pdfEndObj(withKeyword, 0); got != 100 {
		t.Errorf("pdfEndObj = %d, want 100 — the keyword is well inside the window", got)
	}
}

// TestPDFRepairCostStaysLinear is the canary for the whole repair path, not just
// pdfEndObj: any future full-input scan added per object shows up here.
// Before the bound, 4k to 16k objects went from 108ms to 1.7s — 16x for 4x the
// work. c2pa-inspector validates with context.Background(), so there is no
// deadline to cut such a case short; the browser tab simply stops.
// TestPDFRepairCostStaysLinear pins the bound on pdfEndObj. Resolving an
// indirect /Length re-cuts the object, and finding its `endobj` by scanning to
// end of file costs one full pass per repaired object. A document that omits
// the keyword turns that into quadratic work: before the bound, quadrupling the
// objects from 8k to 32k took 440ms to 6.9s, and a 16 MiB input ran for minutes.
// c2pa-inspector validates with context.Background(), so there is no deadline
// to cut it short — the browser tab simply stops.
func TestPDFRepairCostStaysLinear(t *testing.T) {
	const small, factor = 4000, 4

	measure := func(n int) time.Duration {
		data := buildUnterminatedStreams(n)
		start := time.Now()
		pdfJUMBF(context.Background(), data)
		return time.Since(start)
	}
	// Best of three: a loaded machine inflates individual samples, and the
	// minimum is the one least polluted by whatever else is running.
	best := func(n int) time.Duration {
		d := measure(n)
		for range 2 {
			d = min(d, measure(n))
		}
		return d
	}
	base, scaled := best(small), best(small*factor)

	// Linear grows by `factor` (4x), quadratic by factor squared (16x). The
	// midpoint separates them with headroom on both sides.
	const tolerated = factor * 2
	if scaled > base*tolerated {
		t.Errorf("scaling %dx the objects took %.1fx the time (%v -> %v); the repair pass looks quadratic again",
			factor, float64(scaled)/float64(max(base, time.Microsecond)), base, scaled)
	}
	t.Logf("%d objects %v; %d objects %v", small, base.Round(time.Millisecond), small*factor, scaled.Round(time.Millisecond))
}
